services:
  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=VR_Rel_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1111
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vr_app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=VR_Rel_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1111
    depends_on:
      - db