# Generated by Django 5.1.2 on 2025-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
