# Generated by Django 5.1.2 on 2025-01-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persons_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
