# Generated by Django 5.1.2 on 2025-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tasks_is_invite_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важная задача'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_invite',
            field=models.BooleanField(default=False, verbose_name='Пригласить в промо-чат'),
        ),
        migrations.AlterModelTable(
            name='contactstatus',
            table='home_contact_status',
        ),
        migrations.AlterModelTable(
            name='persongame',
            table='home_person_game',
        ),
        migrations.AlterModelTable(
            name='timemanagementlog',
            table='home_time_management_log',
        ),
        migrations.AlterModelTable(
            name='usertask',
            table='home_user_task',
        ),
    ]
