# Generated by Django 5.1.2 on 2025-01-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tasks_is_important_alter_tasks_is_invite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemanagementlog',
            name='person',
        ),
        migrations.AddField(
            model_name='timemanagementlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='home.tasks'),
        ),
    ]
