# Generated by Django 5.1.2 on 2025-01-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_timemanagementlog_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_logs', to='home.tasks')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_comment_log',
            },
        ),
    ]
