# Generated by Django 5.1.2 on 2025-01-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_taskstatus_delete_contactstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_game', to='home.games'),
        ),
        migrations.AlterField(
            model_name='persongame',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_game', to='home.persons'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
