# Generated by Django 5.1.2 on 2025-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_persongame_game_alter_persongame_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
