# Generated by Django 5.1.2 on 2025-01-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='home.tasktype'),
        ),
    ]
