# Generated by Django 5.1.2 on 2025-01-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tasks_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='home.tasktype', verbose_name='Класс задачи'),
        ),
        migrations.AlterModelTable(
            name='tasktype',
            table='task_type',
        ),
    ]
