# Generated by Django 5.1.2 on 2025-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_tasks_task_type_alter_tasktype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_contact',
            field=models.BooleanField(default=True),
        ),
    ]
